name: nexxo_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  go_router: ^12.1.0
  provider: ^6.1.1
  intl: ^0.20.2
  supabase_flutter: ^2.3.0
  glassmorphism: ^3.0.0
  shared_preferences: ^2.2.2
  web: ^1.1.1
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
